apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: monitoring
  name: glances
  labels:
    app: glances
spec:
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      restartPolicy: Always
      hostPID: true
      containers:
        - name: glances
          image: nicolargo/glances:ubuntu-dev
          ports:
            - containerPort: 61208
              hostPort: 61208
              protocol: TCP
            - containerPort: 61209
              hostPort: 61209
              protocol: TCP
          env:
            - name: GLANCES_OPT
              value: "-w"
          securityContext:
            privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: glances
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: glances
  ports:
    - name: tcp-1
      port: 4555
      targetPort: 61208
    - name: tcp-2
      port: 4556
      targetPort: 61209
