{
 "title": "Canopy Dashboard Reloaded",
 "tags": [ "canopy" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(canopy_bft_height,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Height",
   "type": "stat",
   "description": "Current chain's height",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_height{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "description": "Unique identifier for the chain",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_chain_id{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "stat",
   "description": "Balance of the staked node's account",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_account_balance{pod=~\"$node\"} * 0.000001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Staked Amount",
   "type": "stat",
   "description": "Amount staked for this validator",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_stake_amount{pod=~\"$node\"} * 0.000001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Height",
   "type": "stat",
   "description": "Current  root chain's height",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_root_height{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Chain ID",
   "type": "stat",
   "description": "Unique identifier for the Root chain",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_root_chain_id{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_syncing_status{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is active",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_node_status{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compounding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_compounding{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_type{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_status{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Peers",
   "type": "stat",
   "description": "Peers that started the connection with the node",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_peer_inbound{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Peers",
   "type": "stat",
   "description": "Peers that the node started the connection",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_peer_outbound{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "stat",
   "description": "Inbound + outbound peers",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_peer_total{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Software Version",
   "type": "stat",
   "description": "Current software's version",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  canopy_software_version{pod=\"$node\"} * 0 + 1,\n  \"metric_value\", \"$1\", \"version\", \"(.*)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Peers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "canopy_peer_inbound{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Outbound Peers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "canopy_peer_outbound{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Produced Blocks",
   "type": "timeseries",
   "description": "Validator was the block producer",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "canopy_validator_block_producer{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Block Size",
   "type": "stat",
   "description": "Size of the block in bytes",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_size{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Block TXs",
   "type": "stat",
   "description": "The number of transactions in the last block",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_num_txs{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Largest Tx",
   "type": "stat",
   "description": "The largest transactions in the last block",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_largest_txn{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block VDF iterations",
   "type": "stat",
   "description": "The number of VDF iterations in the last canopy block",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_vdf_iterations{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Double Sign",
   "type": "stat",
   "description": "Sum of times the validator did a double sign",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(canopy_validator_double_signer{\"$node\"=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Non Sign",
   "type": "stat",
   "description": "Sum of times the validator did a non sign",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(canopy_validator_non_signer{\"$node\"=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Signers Count",
   "type": "stat",
   "description": "Sum of non signers over the selected period",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(canopy_validator_non_signer_count{\"$node\"=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Double Signers Count",
   "type": "stat",
   "description": "Sum of double signers over the selected period",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(canopy_validator_double_signer_count{\"$node\"=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Processing times",
   "type": "timeseries",
   "description": "The time it takes to process a received block",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_block_processing_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_block_processing_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root Chain Info Times",
   "type": "timeseries",
   "description": "How long does it take to get an update from the Root Chain",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_root_chain_info_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_root_chain_info_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Block TXs",
   "type": "timeseries",
   "description": "The number of transactions in the last block",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "canopy_block_num_txs{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BFT Rounds",
   "type": "timeseries",
   "description": "Rounds of consensus per block",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "canopy_bft_round{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chain Non Signers",
   "type": "timeseries",
   "description": "Chain wide non signers count",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "canopy_validator_non_signer_count{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Validator Non sign",
   "type": "timeseries",
   "description": "Validator non sign count",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "canopy_validator_non_signer{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Non Signers %",
   "type": "timeseries",
   "description": "Chain wide non signers percentage",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "canopy_block_non_signer_percentage{pod=~\"$node\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "BFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Election Phase Times",
   "type": "timeseries",
   "description": "Execution time of the ELECTION bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_election_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_election_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Election Vote Phase Times",
   "type": "timeseries",
   "description": "Execution time of the ELECTION VOTE bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_election_vote_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_election_vote_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Propose Phase Times",
   "type": "timeseries",
   "description": "Execution time of the PROPOSE bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_propose_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_propose_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Propose Vote Phase Times",
   "type": "timeseries",
   "description": "Execution time of the PROPOSE VOTE bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_propose_vote_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_propose_vote_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pre Commit Phase Times",
   "type": "timeseries",
   "description": "Execution time of the PRECOMMIT  bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_precommit_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_precommit_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pre Commit Vote Phase Times",
   "type": "timeseries",
   "description": "Execution time of the PRECOMMIT VOTE  bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_precommit_vote_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_precommit_vote_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Phase Times",
   "type": "timeseries",
   "description": "Execution time of the COMMIT  bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_commit_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_commit_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commit Process Phase Times",
   "type": "timeseries",
   "description": "Execution time of the COMMIT Process  bft phase",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_commit_process_time_sum{pod=\"$node\"}[$__rate_interval]) / rate(canopy_bft_commit_process_time_count{pod=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "description": "Count of bytes in the transaction memory pool",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "canopy_mempool_size{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Tx Count",
   "type": "timeseries",
   "description": "Count of transactions in the transaction memory pool",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "canopy_mempool_tx_count{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Commit Time",
   "type": "timeseries",
   "description": "Execution time of the flushing of the commit batch",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(canopy_store_commit_time_sum{pod=~\"$node\"}[$__rate_interval])) / (sum by(pod) (rate(canopy_store_commit_time_count{pod=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Size",
   "type": "timeseries",
   "description": "Number of bytes in the commit batch",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "canopy_store_commit_size{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Commit Entries",
   "type": "timeseries",
   "description": "Number of individual db entries per commit",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 58 },
   "targets": [
    {
     "expr": "canopy_store_commit_entries{pod=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{pod=\"$node\"}"
    }
   ]
  }
 ]
}